// example/shared-state-integration-vue/vue/src/App.vue
<script setup lang="ts">
import { bridge, isWebViewBridgeAvailable } from "./bridge";
import { useBridge } from "./useBridge";

const handleOpenInAppBrowser = () => {
  if (bridge.isNativeMethodAvailable("openInAppBrowser") === true) {
    bridge.openInAppBrowser("https://github.com/gronxb/webview-bridge");
  }
};

const bridgeStore = useBridge(bridge.store);
</script>

<template>
  <div>
    <div>isWebViewBridgeAvailable {{ isWebViewBridgeAvailable }}</div>
    <h2>This is WebView</h2>

    <button @click="handleOpenInAppBrowser()">open InAppBrowser</button>

    <p>Native Count: {{ bridgeStore.count }}</p>

    <button @click="bridgeStore.increase()">Increase from web</button>

    <div>
      <p>Native Data Text: {{ bridgeStore.data.text }}</p>
      <input
        type="text"
        :value="bridgeStore.data.text"
        @input="
          (e) => bridgeStore.setDataText((e.target as HTMLInputElement).value)
        "
      />
    </div>
  </div>
</template>

// example/web/src/App.tsx
import { useEffect, useState } from "react";
import "./App.css";
import { linkNativeMethod, registerWebMethod } from "@webview-bridge/web";
import type { AppBridge } from "@webview-bridge/example-native";

export const webBridge = registerWebMethod({
  async alert(message: string) {
    window.alert(message);
  },
  async sum(a: number, b: number) {
    return a + b;
  },
});

const nativeMethod = linkNativeMethod<AppBridge>({
  throwOnError: true,
});

function App() {
  const [message, setMessage] = useState("");

  useEffect(() => {
    nativeMethod.getMessage().then((message) => {
      setMessage(message);
    });
  }, []);

  return (
    <div>
      <h1>This is a web page.</h1>
      <h1>{message}</h1>
      <button
        onClick={() => {
          if (nativeMethod.isNativeMethodAvailable("openInAppBrowser")) {
            nativeMethod.openInAppBrowser(
              "https://github.com/gronxb/webview-bridge",
            );
          }
        }}
      >
        open InAppBrowser
      </button>

      <div>
        {`isWebViewBridgeAvailable: ${String(
          nativeMethod.isWebViewBridgeAvailable,
        )}`}
      </div>
    </div>
  );
}

export default App;
