// example/shared-state-integration-vue/vue/src/App.vue
<script setup lang="ts">
import { bridge, isWebViewBridgeAvailable } from "./bridge";
import { useBridge } from "./useBridge";

const handleOpenInAppBrowser = () => {
  if (bridge.isNativeMethodAvailable("openInAppBrowser") === true) {
    bridge.openInAppBrowser("https://github.com/gronxb/webview-bridge");
  }
};

const bridgeStore = useBridge(bridge.store);
</script>

<template>
  <div>
    <div>isWebViewBridgeAvailable {{ isWebViewBridgeAvailable }}</div>
    <h2>This is WebView</h2>

    <button @click="handleOpenInAppBrowser()">open InAppBrowser</button>

    <p>Native Count: {{ bridgeStore.count }}</p>

    <button @click="bridgeStore.increase()">Increase from web</button>

    <div>
      <p>Native Data Text: {{ bridgeStore.data.text }}</p>
      <input
        type="text"
        :value="bridgeStore.data.text"
        @input="
          (e) => bridgeStore.setDataText((e.target as HTMLInputElement).value)
        "
      />
    </div>
  </div>
</template>

// example/shared-state-integration-react/react/src/App.tsx
import "./App.css";
import { linkBridge } from "@webview-bridge/web";
import type { AppBridge } from "@webview-bridge-example-native-method/react-native";
import { useBridge } from "./useBridge";

const bridge = linkBridge<AppBridge>({
  throwOnError: true,
  onReady: () => {
    console.log("nativeMethod is ready");
  },
});

function Count() {
  const count = useBridge(bridge.store, (state) => state.count);

  return <p>Native Count: {count}</p>;
}

function DataText() {
  const text = useBridge(bridge.store, (state) => state.data.text);

  return (
    <div>
      <p>Native Data Text: {text}</p>
      <input
        type="text"
        value={text}
        onChange={(e) => bridge.setDataText(e.target.value)}
      />
    </div>
  );
}

function App() {
  const increase = useBridge(bridge.store, (state) => state.increase);

  return (
    <div>
      <div>
        {`isWebViewBridgeAvailable: ${String(bridge.isWebViewBridgeAvailable)}`}
      </div>

      <button
        onClick={() => {
          if (bridge.isNativeMethodAvailable("openInAppBrowser") === true) {
            bridge.openInAppBrowser("https://github.com/gronxb/webview-bridge");
          }
        }}
      >
        open InAppBrowser
      </button>

      <Count />
      <button
        onClick={() => {
          increase(); // or bridge.increase()
        }}
      >
        Increase from web
      </button>

      <DataText />
    </div>
  );
}

export default App;
