// example/shared-state-integration-vue/vue/src/App.vue
<script setup lang="ts">
import { bridge, isReady } from "./bridge";
import { useBridge } from "@webview-bridge/vue";

const handleOpenInAppBrowser = () => {
  if (bridge.isNativeMethodAvailable("openInAppBrowser") === true) {
    bridge.openInAppBrowser("https://github.com/gronxb/webview-bridge");
  }
};

const bridgeStore = useBridge(bridge.store);
</script>

<template>
  <div v-if="isReady">
    <div>isReady {{ isReady }}</div>
    <h2>This is WebView</h2>

    <button @click="handleOpenInAppBrowser()">open InAppBrowser</button>

    <p>Native Count: {{ bridgeStore.count }}</p>

    <button @click="bridgeStore.increase()">Increase from web</button>

    <div>
      <p>Native Data Text: {{ bridgeStore.data.text }}</p>
      <input
        type="text"
        :value="bridgeStore.data.text"
        @input="
          (e) => bridgeStore.setDataText((e.target as HTMLInputElement).value)
        "
      />
    </div>
  </div>
</template>

// example/react-navigation/react/src/App.tsx
import { useEffect, useState } from "react";
import "./App.css";
import { linkBridge } from "@webview-bridge/web";
import type { AppBridge } from "@webview-bridge-example-react-navigation/react-native";

const bridge = linkBridge<AppBridge>({
  throwOnError: true,
  onReady: () => {
    console.log("bridge is ready");
  },
});

function App() {
  const [userId, setUserId] = useState("");

  return (
    <div>
      <h3>This is a web page.</h3>

      <div
        style={{
          display: "flex",
          flexDirection: "column",
          gap: "12px",
        }}
      >
        <button
          onClick={() => {
            if (bridge.isNativeMethodAvailable("openInAppBrowser") === true) {
              bridge.openInAppBrowser(
                "https://github.com/gronxb/webview-bridge",
              );
            }
          }}
        >
          open InAppBrowser
        </button>

        <input
          type="text"
          style={{
            fontSize: "16px",
          }}
          value={userId}
          onChange={(e) => setUserId(e.target.value)}
          placeholder="please userId"
        />
        <button
          onClick={() => {
            bridge.push("UserInfo", { userId });
          }}
        >
          Go UserInfo
        </button>

        <button
          onClick={async () => {
            if (await bridge.canGoBack()) {
              bridge.goBack();
            } else {
              alert("Can't go back");
            }
          }}
        >
          Go Back
        </button>
      </div>
    </div>
  );
}

export default App;
